// import React from "react";
// import './Mystorybox.css';


// // import BannerImage from   '../../asset/python.png';
// // import ICON from          '../../asset/Logo.png';


// function Gifts() {
//   return (
//     <div className="gift-container">
//       <div className="gift-banner">
//         <img src={""} alt="Banner" className="gift-banner-image" />
//         <h2 className="title">Discover the magic of gifting</h2>
//         <p className="content">Find unique gifts from top companies.</p>
//         <div className="gift-icon">
//           <img className="icon" src={""} alt="Gift Icon" />
//         </div>
//       </div>
//     </div>
//   );
// }

// export default Gifts;
