// import React from "react";
// import './Mystorybox.css';


// // import BannerImage from   '../../asset/python.png';
// // import ICON from          '../../asset/Logo.png';


// function Gifts() {
//   return (
//     <div className="gift-container">
//       <div className="gift-banner">
//         <img src={""} alt="Banner" className="gift-banner-image" />
//         <h2 className="title">Discover the magic of gifting</h2>
//         <p className="content">Find unique gifts from top companies.</p>
//         <div className="gift-icon">
//           <img className="icon" src={""} alt="Gift Icon" />
//         </div>
//       </div>
//     </div>
//   );
// }

// export default Gifts;






    // if (error) {
  //   return <div className="error-message" style={{ width: '100vw', height: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'white' }}>Error: {error}</div>;
  // }
  // if (isLoading) {
  //   return <Loading />;
  // }
  // if (!isTimeOver && advertisers.length !== 0) {
  //   return <CountdownTimer targetTime={advertisers[0].targetTime} />;
  // }
  // if (advertisers.length === 0 && !isLoading) {
  //   return <Nodata />;
  // }
  // if (advertisers.some(ad => ad.active === 'yes' && ad.task_over === 'yes')) {
  //   return <Nodata />; // Show "No data" message if any advertiser is active and task is over
  // }